name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version code
        env:
          TOKEN: ${{ secrets.REPOSITORY_VARS_TOKEN }}
        run: |
          VERSION_CODE=$(( VERSION_CODE+1 ))
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DaoCacao/autoincrement-test/actions/variables/VERSION_CODE \
          -d '{"name":"VERSION_CODE","value":"$VERSION_CODE"}'

      - name: Get version code
        run: echo ${{ vars.VERSION_CODE }}
