name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version code
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DaoCacao/autoincrement-test/actions/variables \
          -d '{"name":"USERNAME","value":"octocat"}'

      - name: Get version code
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DaoCacao/autoincrement-test/actions/variables
