name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version code
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DaoCacao/autoincrement-test/actions/variables \
          -d '{"name":"USERNAME","value":"octocat"}'

      - name: Get version code
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/DaoCacao/autoincrement-test/actions/variables
